version: 1.0.0.{build}
os: Visual Studio 2015
shallow_clone: true
cache:
  - packages -> **\packages.config

before_build: cd .. && git clone https://github.com/bowmark/allauth.lib.git Lib && cd %APPVEYOR_BUILD_FOLDER%
build_script: .\build.bat clean release pkgWin
#test_script: .\build.bat releaseTest

artifacts:
  - path: build\dist\**
